### ISSUE TITLE
bulk converting

### ISSUE THREAD

**Issue by HosinQM** [neocotic/convert-svg#41]
Hello, Can i convert two or more SVG files at same time?

**Comment by neocotic** [comment]
@HosinQM Hello. Yes, you can. However, there's pros and cons to be aware of. You can use `createConverter` to spawn multiple instances of Headless Chromium which you can use for parallel conversions. However, this could be resource intensive and could potentially slow down conversion as opening and closing (via `destroy` - otherwise they'll stay open forever) instances is time consuming. It really depends on much workload you really expect and may require some benchmarking on your solution to pick the right approach.

Another possibility is to create a pool of instances from which you can utilize any that are free or wait until one becomes available. I am currently planning on adding a customizable `createPool` method soon that should do this for you, but I have no ETA on that right now.
